version: '3.8' # Версия формата Docker Compose

services: # Здесь мы перечисляем наши контейнеры (сервисы)

  # 1. Первый контейнер — это наша база данных. Назовем её "db"
  db:
    image: postgres:15-alpine # Не пишем Dockerfile, а берем готовый официальный образ из интернета
    restart: always # Если база упадет, Docker сам её поднимет
    environment: # Переменные окружения. Передаем настройки прямо внутрь базы
      POSTGRES_DB: devops_db # Имя базы
      POSTGRES_USER: linqy # Имя пользователя
      POSTGRES_PASSWORD: supersecret123 # Пароль
    volumes:
      - pgdata:/var/lib/postgresql/data # Лайфхак: привязываем папку базы к диску Ubuntu, чтобы данные не стерлись при перезапуске

  # 2. Второй контейнер — наше Python-приложение. Назовем его "web"
  web:
    build: . # Говорим: "Собери образ по Dockerfile, который лежит в этой же папке"
    restart: always
    ports:
      - "8082:8081" # Пробрасываем мост: порт 8082 на твоей Ubuntu ведет на порт 8081 внутри контейнера
    depends_on:
      - db # Говорим: "Не запускай питон, пока не поднимется контейнер с базой db"

volumes: # Объявляем постоянное хранилище для базы данных
  pgdata:
